package com.logagg.processor.s3;

import com.logagg.common.util.ChunkUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import software.amazon.awssdk.core.sync.RequestBody;
import software.amazon.awssdk.services.s3.S3Client;
import software.amazon.awssdk.services.s3.model.PutObjectRequest;

@Service
public class S3Service {

    private static final Logger log = LoggerFactory.getLogger(S3Service.class);

    private final S3Client s3Client;
    private final String bucket;

    public S3Service(S3Client s3Client, @Value("${s3.bucket:logs-bucket}") String bucket) {
        this.s3Client = s3Client;
        this.bucket = bucket;
    }

    /**
     * Compresses rawNdjson with gzip (best compression) and uploads to S3.
     * The key already ends with .json.gz (generated by ChunkUtils.generateS3Key).
     */
    public void putObject(String key, byte[] rawNdjson) throws Exception {
        byte[] compressed = ChunkUtils.compress(rawNdjson);

        s3Client.putObject(
                PutObjectRequest.builder()
                        .bucket(bucket)
                        .key(key)
                        .contentType("application/gzip")
                        .contentLength((long) compressed.length)
                        .build(),
                RequestBody.fromBytes(compressed)
        );

        log.debug("Uploaded s3Key={} originalBytes={} compressedBytes={}",
                key, rawNdjson.length, compressed.length);
    }
}
